from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetView
from .forms import MyPasswordResetForm, MySetPasswordForm
from . import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
    path("profile/", views.profile, name="profile"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("sign-up/", views.sign_up, name="sign-up"),
    path("diary/", views.diary, name="diary"),
    path("portfolios/", views.portfolios, name="portfolios"), 
    path("add-post/", views.addPost, name="add-post"),
    path("portfolios/edit-stock/<int:id>", views.editStockPage, name="editStock"),
    path("delete/<int:id>", views.deleteStockPage, name="deleteStock"),
    path("portfolios/show-portfolio/<int:id>", views.showPortfolioPage, name="showPortfolio"),
    path("delete-portfolio/<int:id>", views.deletePortfolioPage, name="deletePortfolio"),
    path("history", views.historyPage, name="history"),
    path("show-stock/<int:id>", views.showStockPage, name="showStock"),
    path("delete-sold-stock/<int:id>", views.deleteSoldStock, name="deleteSoldStock"),
    path("change-password/", views.change_password, name="changePassword"),
    path("edit-post/<int:id>", views.editPost, name="editPost"),
    path("delete-post/<int:id>", views.deletePost, name="deletePost"),
    path("password-reset/", views.PasswordResetView.as_view(template_name = "home/password_reset.html", 
                                                            form_class = MyPasswordResetForm, 
                                                            title="Сброс пароля",
                                                            extra_context = {"titlePage": "Сброс пароля"}), 
                                                            name="password_reset"),
    path("password-reset/done/", PasswordResetDoneView.as_view(template_name = "home/password_reset_done.html",
                                                               title="Письмо отправлено",
                                                               extra_context = {"titlePage": "Проверьте почту"}), 
                                                               name="password_reset_done"),
    path("password-reset/confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name = "home/password_reset_confirm.html",
                                                                                      title = "Изменение пароля", extra_context = {"titlePage": "Изменение пароля"},
                                                                                      form_class = MySetPasswordForm), name="password_reset_confirm"),
    path("password-reset/complete/", PasswordResetCompleteView.as_view(template_name = "home/password_reset_complete.html", extra_context = {"titlePage": "Пароль был успешно изменён"},
                                                                        title = "Пароль изменен"), name="password_reset_complete"),
]
