# Generated by Django 4.2.3 on 2023-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.CharField(max_length=4)),
                ('priceRUB', models.FloatField()),
                ('amount', models.IntegerField()),
                ('industry', models.CharField(max_length=50)),
                ('dateBuying', models.DateField()),
            ],
        ),
    ]
