# Generated by Django 4.2.3 on 2023-07-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='Portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.stockportfoliomodel'),
            preserve_default=False,
        ),
    ]
