# Generated by Django 4.2.3 on 2023-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stockmodel_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfoliomodel',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
