# Generated by Django 4.2.3 on 2023-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stockportfoliomodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceOpen', models.FloatField()),
                ('priceClose', models.FloatField()),
                ('priceMax', models.FloatField()),
                ('priceMin', models.FloatField()),
                ('msg', models.TextField()),
                ('date', models.DateField()),
                ('Portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.stockportfoliomodel')),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.stockmodel')),
            ],
        ),
    ]
