# Generated by Django 4.2.3 on 2023-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diarypostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypostmodel',
            name='Portfolio',
        ),
    ]
