# Generated by Django 4.2.3 on 2023-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uniquserstockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypostmodel',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
