# Generated by Django 4.2.3 on 2023-07-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_diarypostmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypostmodel',
            name='Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.uniquserstockmodel'),
        ),
    ]
