# Generated by Django 4.2.3 on 2023-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_diarypostmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypostmodel',
            name='priceMax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diarypostmodel',
            name='priceMin',
            field=models.FloatField(null=True),
        ),
    ]
