# Generated by Django 4.2.3 on 2023-07-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_historymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquserstockmodel',
            name='industry',
        ),
    ]
