# Generated by Django 4.2.3 on 2023-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_uniquserstockmodel_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
