# Generated by Django 4.2.3 on 2023-08-01 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_stockmodel_reasonbuy_stockmodel_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='amountSell',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
