# Generated by Django 4.2.3 on 2023-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_historymodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypostmodel',
            name='Stock',
        ),
        migrations.AddField(
            model_name='diarypostmodel',
            name='stockTick',
            field=models.CharField(default=1245, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UniqUserStockModel',
        ),
    ]
