# Generated by Django 4.2.3 on 2023-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_diarypostmodel_stock_diarypostmodel_stocktick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfoliomodel',
            name='comission',
            field=models.FloatField(default=0.003),
            preserve_default=False,
        ),
    ]
